import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import  Montserrat from "next/font/local";
import "./globals.css";
import Rainbow from "@/utils/rainbow";
import { MiniKitContextProvider } from "@/utils/MiniKitProvider";

// After your app is fully loaded and ready to display


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.className} antialiased`}
      >
        <MiniKitContextProvider>{children}</MiniKitContextProvider>
      </body>
    </html>
  );
}
